name: allure-report

on:
  push:
    branches:
      - main

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Clean Allure and Cypress artifacts
        run: npm run allure:clear

      - name: Download Cypress
        uses: bahmutov/npm-install@v1
        with:
          install-command: npm ci

      - name: Cache Cypress binary
        uses: actions/cache@v2
        with:
          path: ~/.cache/Cypress
          key: cypress-cache-v2-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            cypress-cache-v2-${{ runner.os }}-

      - name: Run pretest
        run: npm run pretest

      - name: Run Cypress tests
        run: |
          npm run cy:run
          npm run cy:cucumber:run
        env:
          CYPRESS_SPLIT_SPEC_API_KEY: '${{ secrets.SPLIT_SPEC_API_KEY }}'

      - name: Install Allure
        run: |
          npm install --save-dev allure
          npm install -g allure-commandline

      - name: Generate Allure Report
        run: npm run allure:report

      - name: Move Allure Report history
        run: npm run allure:history

      - name: Configure Git
        run: |
          git config --local user.email "emyzheng80@gmail.com"
          git config --local user.name "GitHub Actions"
        shell: bash

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Update Allure report"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
