name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Configure Git
      run: |
        git config --global user.name 'yeungemy'
        git config --global user.email 'emyzheng80@gmail.com'

    - name: Install dependencies
      run: npm install

    - name: Run pretest script
      run: npm run pretest

    - name: Run test script
      run: npm run test

    - name: Install Webpack
      run: npm install webpack --save-dev

    - name: Generate Allure report
      run: npm run allure:report

    - name: Install Allure command-line tool
      run: |
        sudo apt-add-repository ppa:qameta/allure
        sudo apt-get update
        sudo apt-get install allure

    - name: Commit and push Allure report
      run: |
        git add .
        git commit -m "Add Allure report"
        git push
