name: allure-report

on:
  push:
    branches:
      - main

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Download Cypress
        uses: bahmutov/npm-install@v1
        with:
          install-command: npm ci

      - name: Cache Cypress binary
        uses: actions/cache@v2
        with:
          path: ~/.cache/Cypress
          key: cypress-cache-v2-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            cypress-cache-v2-${{ runner.os }}-

      - name: Run Cypress
        run: npm run cy:run
        env:
          CYPRESS_SPLIT_SPEC_API_KEY: '${{ secrets.SPLIT_SPEC_API_KEY }}'

      - name: Run Cypress Cucumber
        run: npm run cy:cucumber:run
        if: always()

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        with:
          ref: allure
          path: allure

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          gh_pages: allure

      - name: Deploy report to GitHub Pages
        if: always()
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git checkout -b allure
          git add .
          git commit -m "Update Allure report"
          git push origin allure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
